# Generated by Django 4.2 on 2023-04-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
